// <auto-generated />
using System;
using EnSyncPortal.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnSyncPortal.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20181220040917_SwitchedToUpperCase")]
    partial class SwitchedToUpperCase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnSyncPortal.Models.Employee", b =>
                {
                    b.Property<long>("EMPLOYEE_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CONTROL_ID");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("FIRST_NAME");

                    b.Property<string>("GENDER");

                    b.Property<string>("LAST_NAME");

                    b.Property<string>("SSN");

                    b.HasKey("EMPLOYEE_ID");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
