// <auto-generated />
using System;
using EnSyncPortal.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnSyncPortal.Migrations.EmployeeProfile
{
    [DbContext(typeof(EmployeeProfileContext))]
    [Migration("20181220041731_AddedNewDepartmentTable")]
    partial class AddedNewDepartmentTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnSyncPortal.Models.EmployeeProfile", b =>
                {
                    b.Property<long>("EMPLOYEE_PROFILE_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CONTROL_ID");

                    b.Property<string>("COUNTRY");

                    b.Property<long>("DEPARTMENT_ID");

                    b.Property<long>("EMPLOYEE_ID");

                    b.Property<string>("EMPLOYMENT_TYPE");

                    b.Property<DateTime>("HIRE_DATE");

                    b.Property<long>("PROJECT_ID");

                    b.Property<float>("SALARY_AMOUNT");

                    b.Property<DateTime>("TIME_STAMP");

                    b.HasKey("EMPLOYEE_PROFILE_ID");

                    b.ToTable("EmployeeProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
